from pywatts.modules.generation.anomaly_generation_module import AnomalyGeneration
from pywatts.modules.generation.energy_anomaly_generation_module import EnergyAnomalyGeneration
from pywatts.modules.generation.power_anomaly_generation_module import PowerAnomalyGeneration
